### ISSUE TITLE
Option to replace all name servers instead of prepending

### ISSUE THREAD

**Issue by andyshinn** [gliderlabs/resolvable#2]
It might be nice to have an option to replace all `nameserver` in the `resolv.conf` instead of just prepending itself. This way it would have better compatibility with musl libc based containers.

**Comment by mgood** [comment]
Since ef006554e60727fd35da101601105499577b81d4, existing lines in the resolv.conf are commented out when resolvable starts, so it should be the only nameserver entry left uncommented.
