### ISSUE TITLE
Document reasons for use (eg, vs dnsmasq)

### ISSUE THREAD

**Issue by pikeas** [gliderlabs/resolvable#9]
@progrium suggested using resolvable as an alternative to dnsmasq at https://github.com/gliderlabs/docker-alpine/issues/8.

What prompted the creation of resolvable? Are there any downsides to using resolvable instead of dnsmasq?

**Comment by progrium** [comment]
Well resolvable was originally based on dnsmasq but we ran into some quirks that worked against our goals. I mean, if you just read the docs (though I get that they aren't great now), they should show the benefits of resolvable vs dnsmasq ...

**Comment by pikeas** [comment]
Explicit is better than implicit. Resolvable is obviously much simpler and easier to use, but the docs should address this directly, and call out catches (stability, performance) if any.

**Comment by progrium** [comment]
Docs have a long way to go, I agree. But I'm going to close this out because it's already on our radar and I don't really think we need to track it.
